name = "woodgrain-ops"
compatibility_date = "2026-06-08"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "woodgrain_ops"
database_id = "a7a913ce-249e-45d3-8511-876e15dbedef"
