CREATE TABLE IF NOT EXISTS purchase_orders (
  id TEXT PRIMARY KEY,
  po_no TEXT NOT NULL,
  source_pi_id TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  vendor TEXT NOT NULL DEFAULT '',
  vendor_address TEXT NOT NULL DEFAULT '',
  vendor_contact TEXT NOT NULL DEFAULT '',
  vendor_email TEXT NOT NULL DEFAULT '',
  vendor_tel TEXT NOT NULL DEFAULT '',
  vendor_fax TEXT NOT NULL DEFAULT '',
  customer TEXT NOT NULL DEFAULT '',
  our_ref_no TEXT NOT NULL DEFAULT '',
  delivery_date TEXT NOT NULL DEFAULT '',
  deliver_to TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Draft',
  item_code TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  product_type TEXT NOT NULL DEFAULT '',
  size TEXT NOT NULL DEFAULT '',
  colors TEXT NOT NULL DEFAULT '',
  finished TEXT NOT NULL DEFAULT '',
  remarks TEXT NOT NULL DEFAULT '',
  lines_json TEXT NOT NULL DEFAULT '[]',
  packing_rows_json TEXT NOT NULL DEFAULT '[]',
  notes TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT ''
);

INSERT OR IGNORE INTO purchase_orders (
  id,
  po_no,
  source_pi_id,
  date,
  vendor,
  vendor_address,
  vendor_contact,
  vendor_email,
  vendor_tel,
  vendor_fax,
  customer,
  our_ref_no,
  delivery_date,
  deliver_to,
  status,
  item_code,
  description,
  product_type,
  size,
  colors,
  finished,
  remarks,
  lines_json,
  packing_rows_json,
  notes,
  image_url
) VALUES (
  'PO001',
  'PO2603428',
  'PI001',
  '2026-06-11',
  '浙江嘉兴市壹佳印刷有限公司',
  '浙江嘉兴市海盐县百步经济开发区百步大道东海棠路288号\n中国',
  'Jason(江先生)',
  'Jason@ye-prt.com',
  '0573-86788092',
  '0573-86788092',
  'KITH',
  'S26060068',
  '2026-06-18',
  '',
  'Confirmed',
  'KITH-TPC10-KHWA080084',
  'KITH Women''s 2025 Tear Away Standard Apparel CCL - 60mm x 20mm',
  '20mm PMS 19-0303 TCX Grosgrain Tape',
  '60mm x 20mm',
  '12-5202 TCX On One Side Only',
  'Square Cut, With Perforation on Top',
  '请跟AI和批版质量做货！',
  '[{"itemCode":"KITH-TPC10-KHWA080084","itemDescription":"KITH Women''s 2025 Tear Away Standard Apparel CCL - 60mm x 20mm","quantity":0.24,"unitPrice":430}]',
  '[{"lot":"1","size":"","quantity":240}]',
  '采购单样式参考',
  ''
);
