CREATE TABLE IF NOT EXISTS developments (
  id TEXT PRIMARY KEY,
  development_no TEXT NOT NULL,
  date TEXT NOT NULL,
  modification_date TEXT NOT NULL,
  register TEXT NOT NULL DEFAULT '',
  item_type TEXT NOT NULL DEFAULT '',
  brand TEXT NOT NULL DEFAULT '',
  linkman TEXT NOT NULL DEFAULT '',
  salesperson TEXT NOT NULL DEFAULT '',
  customer TEXT NOT NULL DEFAULT '',
  item TEXT NOT NULL DEFAULT '',
  product_code TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Draft',
  source_quote_id TEXT NOT NULL DEFAULT '',
  source_quote_no TEXT NOT NULL DEFAULT '',
  lines_json TEXT NOT NULL DEFAULT '[]',
  image_url TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT ''
);

INSERT OR IGNORE INTO developments (
  id,
  development_no,
  date,
  modification_date,
  register,
  item_type,
  brand,
  linkman,
  salesperson,
  customer,
  item,
  product_code,
  product_name,
  status,
  source_quote_id,
  source_quote_no,
  lines_json,
  image_url,
  notes
) VALUES (
  'DE001',
  'DV2606001',
  '2026-06-05',
  '2026-06-07',
  '朱佳毅',
  'STONEY CLOVER LANE 感恩卡、信封和贴纸',
  'STONEY CLOVER LANE',
  'Anly',
  'Jason',
  'GMS',
  '感恩卡 / 信封 / 贴纸',
  'SCL-001',
  '感恩卡 / 信封 / 贴纸',
  'In progress',
  'QU001',
  '2606009',
  '[{"checked":true,"imageUrl":"https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80","productCode":"SCL-TK-001","productName":"300克书纸 感恩卡","description":"TYPE: 300克书纸（参考 APPA-T04）\\nSIZE: 6.25\" x 9\" Folded 6.25\" x 4.25\"\\nCOLOR: PMS 11-0104 TCX, PMS 18-5622 TCX, PMS 555C\\nFINISHED: 啤形，压折位线对折\\nREMARKS: 参考原版结构","typeValue":"300克书纸（参考 APPA-T04）","sizeValue":"6.25\" x 9\" Folded 6.25\" x 4.25\"","colorValue":"PMS 11-0104 TCX, PMS 18-5622 TCX, PMS 555C","finishedValue":"啤形，压折位线对折","remarksValue":"参考原版结构","specLocked":true},{"checked":true,"imageUrl":"https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=800&q=80","productCode":"SCL-ENV-001","productName":"信封","description":"TYPE: 180克书纸信封\\nSIZE: 6.5\" x 4.75\" + 3\" Flap\\nCOLOR: 双面印 PMS 7621C，双面过哑油\\nFINISHED: 啤形，做成信封袋，开口处粘2条双面胶\\nREMARKS: 包含贴纸加工","typeValue":"180克书纸信封","sizeValue":"6.5\" x 4.75\" + 3\" Flap","colorValue":"双面印 PMS 7621C，双面过哑油","finishedValue":"啤形，做成信封袋，开口处粘2条双面胶","remarksValue":"包含贴纸加工","specLocked":true}]',
  'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
  '开发阶段先按样品走，不展示价格。'
);
