export const seedProducts = [
  {
    id: "SPU001",
    name: "莫兰迪色系连衣裙",
    categoryKey: "clothing",
    price: 199,
    stock: 100,
    status: "In stock",
    imageUrl: "",
  },
  {
    id: "SPU002",
    name: "浅紫简约T恤",
    categoryKey: "clothing",
    price: 99,
    stock: 200,
    status: "In stock",
    imageUrl: "",
  },
  {
    id: "SPU003",
    name: "木纹文件收纳盒",
    categoryKey: "office",
    price: 68,
    stock: 74,
    status: "Low stock",
    imageUrl: "",
  },
  {
    id: "SPU004",
    name: "桌面储物托盘",
    categoryKey: "home",
    price: 58,
    stock: 0,
    status: "Out of stock",
    imageUrl: "",
  },
] as const;

export const seedOrders = [
  {
    id: "OR24001",
    customer: "杭州轻岛贸易",
    product: "莫兰迪色系连衣裙",
    status: "Paid",
    total: 1990,
    channel: "线上",
  },
  {
    id: "OR24002",
    customer: "星河商贸",
    product: "浅紫简约T恤",
    status: "Packed",
    total: 1188,
    channel: "门店",
  },
  {
    id: "OR24003",
    customer: "北辰选品",
    product: "木纹文件收纳盒",
    status: "Shipped",
    total: 1360,
    channel: "批发",
  },
  {
    id: "OR24004",
    customer: "云栖生活",
    product: "桌面储物托盘",
    status: "Pending",
    total: 580,
    channel: "线上",
  },
] as const;

export const seedContracts = [
  {
    id: "CT-001",
    title: "商品供货框架协议",
    client: "杭州轻岛贸易",
    status: "Active",
    amount: 186000,
    deadline: "2026-08-16",
  },
  {
    id: "CT-002",
    title: "年度采购合作合同",
    client: "星河商贸",
    status: "Review",
    amount: 390000,
    deadline: "2026-07-04",
  },
  {
    id: "CT-003",
    title: "渠道分销补充协议",
    client: "北辰选品",
    status: "Draft",
    amount: 126000,
    deadline: "2026-06-28",
  },
  {
    id: "CT-004",
    title: "企业服务续约合同",
    client: "云栖生活",
    status: "Expired",
    amount: 520000,
    deadline: "2026-04-10",
  },
] as const;

export const seedBrands = [
  {
    id: "BR001",
    name: "STONEY CLOVER LANE",
    code: "SCL-001",
    customer: "GMS",
    supplier: "Anly",
    country: "US",
    status: "Active",
    owner: "Jason",
    notes: "贴纸 / 信封 / 纸卡",
  },
  {
    id: "BR002",
    name: "SYNSHOO",
    code: "SYN-2606",
    customer: "SYNSHOO LA INC",
    supplier: "ZheJiang Factory",
    country: "US",
    status: "Active",
    owner: "Linda",
    notes: "吊牌 / 商业发票",
  },
  {
    id: "BR003",
    name: "GLOBAL ERP DEMO",
    code: "GRP-1001",
    customer: "Sample Customer",
    supplier: "Internal",
    country: "CN",
    status: "Inactive",
    owner: "Cheese",
    notes: "用于测试品牌关联",
  },
] as const;

export const seedCustomers = [
  {
    id: "CU001",
    name: "GMS",
    code: "GMS-001",
    country: "US",
    contact: "Amy",
    phone: "+1-202-555-0142",
    email: "amy@gms.com",
    address: "New York, US",
    status: "Active",
    notes: "品牌客户",
  },
  {
    id: "CU002",
    name: "SYNSHOO LA INC",
    code: "SYNSHOO-001",
    country: "US",
    contact: "Jason",
    phone: "+1-310-555-0198",
    email: "jason@synshoo.com",
    address: "Los Angeles, US",
    status: "Active",
    notes: "形式发票客户",
  },
] as const;

export const seedSuppliers = [
  {
    id: "SU001",
    name: "Anly",
    code: "SUP-ANLY",
    country: "CN",
    contact: "Linda",
    phone: "86-021-5555",
    email: "linda@anly.cn",
    address: "Shanghai, CN",
    status: "Active",
    notes: "印刷与加工",
  },
  {
    id: "SU002",
    name: "ZheJiang Factory",
    code: "SUP-ZJ",
    country: "CN",
    contact: "Mr. Wang",
    phone: "86-0571-5555",
    email: "wang@zjfactory.cn",
    address: "Zhejiang, CN",
    status: "Active",
    notes: "样品生产",
  },
] as const;

export const seedQuotes = [
  {
    id: "QU001",
    quoteNo: "2606009",
    date: "2026-06-03",
    modificationDate: "2026-06-03",
    register: "朱佳毅",
    itemType: "STONEY CLOVER LANE 感恩卡、信封和贴纸",
    brand: "STONEY CLOVER LANE",
    linkman: "Anly",
    salesperson: "Jason",
    customer: "GMS",
    item: "感恩卡 / 信封 / 贴纸",
    productCode: "SCL-001",
    productName: "感恩卡 / 信封 / 贴纸",
    status: "Approved",
    costItems: [
      { label: "纸", amount: 0.18 },
      { label: "印刷", amount: 0.12 },
      { label: "哑油", amount: 0.04 },
      { label: "工艺", amount: 0.07 },
    ],
    tiers: [
      { quantity: "1M", unitPrice: 0.52 },
      { quantity: "2.5M", unitPrice: 0.41 },
      { quantity: "5M", unitPrice: 0.33 },
    ],
    lines: [
      {
        checked: true,
        imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80",
        productCode: "SCL-TK-001",
        productName: "300克书纸 感恩卡",
        price: 0,
        sample: 0,
        description: "TYPE: 300克书纸（参考 APPA-T04）\nSIZE: 6.25\" x 9\" Folded 6.25\" x 4.25\"\nCOLOR: PMS 11-0104 TCX, PMS 18-5622 TCX, PMS 555C\nFINISHED: 啤形，压折位线对折\nREMARKS: 参考原版结构",
        pricingNotes: "1M:900/M\n2.5M:720/M\n5M:690/M",
        cost: "900/M",
      },
      {
        checked: true,
        imageUrl: "https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=800&q=80",
        productCode: "SCL-ENV-001",
        productName: "信封",
        price: 0,
        sample: 0,
        description: "TYPE: 180克书纸信封\nSIZE: 6.5\" x 4.75\" + 3\" Flap\nCOLOR: 双面印 PMS 7621C，双面过哑油\nFINISHED: 啤形，做成信封袋，开口处粘2条双面胶\nREMARKS: 包含贴纸加工",
        pricingNotes: "1M:1350/M\n2.5M:1150/M\n5M:1100/M",
        cost: "1350/M",
      },
      {
        checked: false,
        imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80",
        productCode: "SCL-STK-001",
        productName: "贴纸",
        price: 0,
        sample: 0,
        description: "TYPE: 300克书纸贴纸\nSIZE: 6.25\" x 9\" 适配折页\nCOLOR: CMYK + PMS 11-0104 TCX\nFINISHED: 四周圆角，局部镂空\nREMARKS: 可按批版调整",
        pricingNotes: "1M:900/M\n2.5M:720/M\n5M:690/M",
        cost: "900/M",
      },
    ],
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80",
    notes: "按订单量自动匹配档位",
  },
] as const;

export const seedPIs = [
  {
    id: "PI001",
    piNo: "PO2603428",
    customer: "KITH",
    brand: "KITH",
    vendor: "浙江嘉兴市壹佳印刷有限公司",
    ourRefNo: "S26060068",
    deliveryDate: "2026-06-18",
    deliverTo: "",
    status: "Generated",
    generatedAt: "2026-06-11T00:00:00Z",
    generatedBy: "Jason",
    pdfUrl: "",
    itemCode: "KITH-TPC10-KHWA080084",
    description: "KITH Women's 2025 Tear Away Standard Apparel CCL - 60mm x 20mm",
    productType: "20mm PMS 19-0303 TCX Grosgrain Tape",
    size: "60mm x 20mm",
    colors: "12-5202 TCX On One Side Only",
    finished: "Square Cut, With Perforation on Top",
    remarks: "请跟AI和批版质量做货！",
    imageUrl: "",
    sizeDetails: [{ size: "0.240 M", quantity: 240 }],
    lines: [
      {
        productCode: "KITH-TPC10-KHWA080084",
        productName: "KITH Women's 2025 Tear Away Standard Apparel CCL - 60mm x 20mm",
        quantity: 0.24,
        unitPrice: 430,
      },
    ],
    notes: "对应采购单：请跟AI和批版质量做货！",
  },
] as const;

export const seedPOs = [
  {
    id: "PO001",
    poNo: "PO2603428",
    sourcePiId: "PI001",
    date: "2026-06-11",
    vendor: "浙江嘉兴市壹佳印刷有限公司",
    vendorAddress: "浙江嘉兴市海盐县百步经济开发区百步大道东海棠路288号\n中国",
    vendorContact: "Jason(江先生)",
    vendorEmail: "Jason@ye-prt.com",
    vendorTel: "0573-86788092",
    vendorFax: "0573-86788092",
    customer: "KITH",
    ourRefNo: "S26060068",
    deliveryDate: "2026-06-18",
    deliverTo: "",
    status: "Confirmed",
    itemCode: "KITH-TPC10-KHWA080084",
    description: "KITH Women's 2025 Tear Away Standard Apparel CCL - 60mm x 20mm",
    productType: "20mm PMS 19-0303 TCX Grosgrain Tape",
    size: "60mm x 20mm",
    colors: "12-5202 TCX On One Side Only",
    finished: "Square Cut, With Perforation on Top",
    remarks: "请跟AI和批版质量做货！",
    lines: [
      {
        itemCode: "KITH-TPC10-KHWA080084",
        itemDescription: "KITH Women's 2025 Tear Away Standard Apparel CCL - 60mm x 20mm",
        quantity: 0.24,
        unitPrice: 430,
      },
    ],
    packingRows: [{ lot: "1", size: "", quantity: 240 }],
    notes: "采购单样式参考",
    imageUrl: "",
  },
] as const;
